name: appsolutely
description: Flutter Starter App
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  fluro: ^1.6.3
  provider: ^4.1.3
  shared_preferences: ^0.5.7+3
  logging: ^0.11.4
dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_intl:
  enabled: true
